Manually remove old/deprecated @types/eslint-scope package (legacy dependency of webpack) which causes error TS2416 with the build-declaration script under eslint@10.